services:
  app:
    image: olegrand1976/activibe-app:latest
    container_name: bookyourcoach_app_prod
    restart: unless-stopped
    # Pas d'exposition de ports - communication interne uniquement
    env_file:
      - production.env
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
    volumes:
      - app_storage:/var/www/storage
      - app_bootstrap_cache:/var/www/bootstrap/cache
      - ssl_certs:/etc/ssl/certs
    depends_on:
      - mysql
      - redis
    networks:
      - bookyourcoach_network

  mysql:
    image: mysql:8.0
    container_name: bookyourcoach_mysql_prod
    restart: unless-stopped
    env_file:
      - production.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
    # Pas d'exposition de ports - communication interne uniquement
    networks:
      - bookyourcoach_network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: bookyourcoach_redis_prod
    restart: unless-stopped
    env_file:
      - production.env
    volumes:
      - redis_data:/data
    # Pas d'exposition de ports - communication interne uniquement
    networks:
      - bookyourcoach_network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

  webserver:
    image: nginx:alpine
    container_name: bookyourcoach_webserver_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - app_storage:/var/www/storage
      - ssl_certs:/etc/ssl/certs
    depends_on:
      - app
    networks:
      - bookyourcoach_network

volumes:
  mysql_data:
    driver: local
  mysql_logs:
    driver: local
  redis_data:
    driver: local
  app_storage:
    driver: local
  app_bootstrap_cache:
    driver: local
  ssl_certs:
    driver: local

networks:
  bookyourcoach_network:
    driver: bridge