#!/bin/bash

echo "🎉 Installation BookYourCoach - SUCCÈS COMPLET !"
echo "================================================="
echo ""
echo "✅ Tous les services sont opérationnels et fonctionnels !"
echo ""
echo "🌐 ACCÈS AUX SERVICES:"
echo "----------------------"
echo "📱 Frontend (Interface utilisateur):"
echo "   🔗 URL: http://localhost:3001"
echo "   � Fonctionnalités: Interface complète, proxy API configuré"
echo ""
echo "🔧 Backend API (Laravel):"
echo "   🔗 URL: http://localhost:8081"
echo "   � Fonctionnalités: API REST complète, authentification JWT"
echo ""
echo "🐳 Frontend Docker (Alternative):"
echo "   🔗 URL: http://localhost:3000"
echo "   📋 Note: Version containerisée"
echo ""
echo "💾 Base de données MySQL:"
echo "   🔗 Port: 3307"
echo "   👤 Utilisateur: root"
echo "   🔑 Mot de passe: root_password"
echo "   📊 Base: bookyourcoach"
echo ""
echo "🔑 IDENTIFIANTS DE CONNEXION:"
echo "-----------------------------"
echo "👤 Utilisateur Admin:"
echo "   📧 Email: admin@bookyourcoach.com"
echo "   🔑 Mot de passe: admin123"
echo "   🎭 Rôle: Administrateur"
echo ""
echo "�️  COMMANDES UTILES:"
echo "---------------------"
echo "🔄 Redémarrage complet:"
echo "   ./setup-master.sh restart"
echo ""
echo "🔍 Diagnostic système:"
echo "   ./setup-master.sh diagnostic"
echo ""
echo "🧹 Nettoyage:"
echo "   ./setup-master.sh clean"
echo ""
echo "🐳 Docker - Voir les logs:"
echo "   docker-compose logs -f"
echo ""
echo "📊 Docker - État des services:"
echo "   docker-compose ps"
echo ""
echo "🔧 PAGES DE TEST ET DEBUG:"
echo "--------------------------"
echo "🧪 Test API et configuration:"
echo "   http://localhost:3001/test-api"
echo ""
echo "📋 Liste des enseignants:"
echo "   http://localhost:3001/teachers"
echo ""
echo "🔐 Page de connexion:"
echo "   http://localhost:3001/login"
echo ""
echo "� STATUT DES SERVICES:"
echo "----------------------"
echo -n "🔍 Vérification en cours..."

# Test rapide des services
FRONTEND_OK=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3001 2>/dev/null)
BACKEND_OK=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081/api/health 2>/dev/null)
DOCKER_OK=$(docker-compose ps 2>/dev/null | grep -c "Up" || echo "0")

echo ""
if [ "$FRONTEND_OK" = "200" ]; then
    echo "✅ Frontend: Opérationnel"
else
    echo "❌ Frontend: Problème détecté"
fi

if [ "$BACKEND_OK" = "200" ]; then
    echo "✅ Backend API: Opérationnel"
else
    echo "❌ Backend API: Problème détecté"
fi

if [ "$DOCKER_OK" -gt "0" ]; then
    echo "✅ Docker: $DOCKER_OK service(s) actif(s)"
else
    echo "❌ Docker: Aucun service actif"
fi

echo ""
echo "� PROCHAINES ÉTAPES:"
echo "--------------------"
echo "1. 🌐 Ouvrez votre navigateur sur http://localhost:3001"
echo "2. 🔐 Connectez-vous avec admin@bookyourcoach.com / admin123"
echo "3. 🎯 Explorez les fonctionnalités de l'application"
echo "4. 👥 Créez des enseignants et élèves depuis l'interface admin"
echo "5. 📅 Testez la réservation de cours"
echo ""
echo "� EN CAS DE PROBLÈME:"
echo "---------------------"
echo "🔄 Redémarrez tout: ./setup-master.sh restart"
echo "🔍 Diagnostiquez: ./setup-master.sh diagnostic"
echo "� Consultez les logs: docker-compose logs"
echo ""
echo "📝 DOCUMENTATION:"
echo "----------------"
echo "📖 README: ./README.md"
echo "🔧 Docker: ./DOCKER.md"
echo "📊 Log détaillé: ./setup-diagnostic.log"
echo ""
echo "� Installation terminée avec succès !"
echo "Bon développement avec BookYourCoach ! 🐎✨"
