// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/17/2025, 4:09:44 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/workspace/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/frontend/plugins/**/*.{js,ts,mjs}","/workspace/frontend/composables/**/*.{js,ts,mjs}","/workspace/frontend/utils/**/*.{js,ts,mjs}","/workspace/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspace/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspace/frontend/app.config.{js,ts,mjs}"]}},
{"theme":{"extend":{"colors":{"primary":{"50":"#fdf7f0","100":"#fbeee0","200":"#f5d9c1","300":"#efc19c","400":"#e8a575","500":"#d4824a","600":"#c26d3f","700":"#a15634","800":"#814530","900":"#693829"}},"fontFamily":{"serif":["Merriweather","ui-serif","Georgia"]},"backgroundImage":{"gradient-radial":"radial-gradient(var(--tw-gradient-stops))","gradient-conic":"conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))"}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;