<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class LessonRecurringSlot extends Model
{
    use HasFactory;

    protected $fillable = [
        'lesson_id',
        'recurring_slot_id',
        'subscription_instance_id',
        'generated_at',
        'generated_by',
    ];

    protected $casts = [
        'generated_at' => 'datetime',
    ];

    /**
     * Le cours associé
     */
    public function lesson(): BelongsTo
    {
        return $this->belongsTo(Lesson::class);
    }

    /**
     * Le créneau récurrent associé
     */
    public function recurringSlot(): BelongsTo
    {
        return $this->belongsTo(RecurringSlot::class);
    }

    /**
     * L'instance d'abonnement qui a payé pour ce cours
     */
    public function subscriptionInstance(): BelongsTo
    {
        return $this->belongsTo(SubscriptionInstance::class);
    }

    /**
     * Vérifie si le cours a été généré automatiquement
     */
    public function isAutoGenerated(): bool
    {
        return $this->generated_by === 'auto';
    }

    /**
     * Vérifie si le cours a été créé manuellement
     */
    public function isManualGenerated(): bool
    {
        return $this->generated_by === 'manual';
    }
}
