import { library, config } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { 
  faUser, 
  faEnvelope, 
  faLock, 
  faCalendar,
  faUsers,
  faHome,
  faCog,
  faSignOutAlt,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faCheck,
  faTimes,
  faSearch,
  faChevronLeft,
  faChevronRight,
  faBars,
  faArrowRight,
  faArrowLeft,
  faSwimmingPool,
  faDumbbell,
  faHorse,
  faFutbol,
  faTableTennis,
  faBiking,
  faRunning,
  faHeartbeat,
  faClock,
  faMapMarkerAlt,
  faPhone,
  faGlobe,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faStar,
  faEye,
  faEyeSlash,
  faDownload,
  faUpload,
  faFilter,
  faSave,
  faFileAlt,
  faChartBar,
  faBell,
  faUserCircle,
  faBuilding,
  faCalendarCheck,
  faCalendarPlus
} from '@fortawesome/free-solid-svg-icons'

// Configuration FontAwesome
config.autoAddCss = false

// Ajouter les icônes à la bibliothèque
library.add(
  faUser,
  faEnvelope,
  faLock,
  faCalendar,
  faUsers,
  faHome,
  faCog,
  faSignOutAlt,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faCheck,
  faTimes,
  faSearch,
  faChevronLeft,
  faChevronRight,
  faBars,
  faArrowRight,
  faArrowLeft,
  faSwimmingPool,
  faDumbbell,
  faHorse,
  faFutbol,
  faTableTennis,
  faBiking,
  faRunning,
  faHeartbeat,
  faClock,
  faMapMarkerAlt,
  faPhone,
  faGlobe,
  faInfoCircle,
  faExclamationTriangle,
  faCheckCircle,
  faTimesCircle,
  faStar,
  faEye,
  faEyeSlash,
  faDownload,
  faUpload,
  faFilter,
  faSave,
  faFileAlt,
  faChartBar,
  faBell,
  faUserCircle,
  faBuilding,
  faCalendarCheck,
  faCalendarPlus
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('font-awesome-icon', FontAwesomeIcon)
})


