// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/08/2025 17:26:00
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/olivier/projets/bookyourcoach/copilot/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/plugins/**/*.{js,ts,mjs}","/home/olivier/projets/bookyourcoach/copilot/frontend/composables/**/*.{js,ts,mjs}","/home/olivier/projets/bookyourcoach/copilot/frontend/utils/**/*.{js,ts,mjs}","/home/olivier/projets/bookyourcoach/copilot/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/app.config.{js,ts,mjs}"]}},
{"theme":{"extend":{"colors":{"primary":{"50":"#eff6ff","100":"#dbeafe","200":"#bfdbfe","300":"#93c5fd","400":"#60a5fa","500":"#3b82f6","600":"#2563eb","700":"#1d4ed8","800":"#1e40af","900":"#1e3a8a"}}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;