// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/08/2025 06:22:21
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/olivier/projets/bookyourcoach/copilot/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/plugins/**/*.{js,ts,mjs}","/home/olivier/projets/bookyourcoach/copilot/frontend/composables/**/*.{js,ts,mjs}","/home/olivier/projets/bookyourcoach/copilot/frontend/utils/**/*.{js,ts,mjs}","/home/olivier/projets/bookyourcoach/copilot/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/olivier/projets/bookyourcoach/copilot/frontend/app.config.{js,ts,mjs}"]}},
{"theme":{"extend":{"colors":{"primary":{"50":"#fdf7f0","100":"#fbeee0","200":"#f5d9c1","300":"#efc19c","400":"#e8a575","500":"#d4824a","600":"#c26d3f","700":"#a15634","800":"#814530","900":"#693829"},"equestrian":{"brown":"#8B4513","darkBrown":"#654321","leather":"#D2691E","gold":"#DAA520","cream":"#F5F5DC","forest":"#228B22"}},"fontFamily":{"serif":["Merriweather","ui-serif","Georgia"]},"backgroundImage":{"stable-gradient":"linear-gradient(135deg, #8B4513 0%, #D2691E 50%, #DAA520 100%)","horse-pattern":"url('data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\"><path d=\"M20 20h60v60H20z\" fill=\"%23f5f5dc\" opacity=\"0.1\"/></svg>')"}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;